"""Initial Migration

Revision ID: 4f2737e844cb
Revises: 
Create Date: 2025-12-30 02:31:27.247544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f2737e844cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('price_from_market', sa.FLOAT(), nullable=False),
    sa.Column('market_commission', sa.FLOAT(), nullable=False),
    sa.Column('market_costs', sa.FLOAT(), nullable=False),
    sa.Column('discount', sa.FLOAT(), nullable=False),
    sa.Column('product_series', sa.String(length=255), nullable=False),
    sa.Column('shipping_date', sa.DATE(), nullable=False),
    sa.Column('preliminary_costs', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
